# Generated by Django 3.2.5 on 2021-08-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
