# Generated by Django 3.2.5 on 2021-08-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_comments_blogcomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomments',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost'),
        ),
    ]
