# Generated by Django 3.2.5 on 2021-08-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogcomment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_on',
        ),
    ]
